apiVersion: v1
kind: Namespace
metadata:
  name: devsecops-demo
  labels:
    app.kubernetes.io/part-of: devops-s17-devsecops-demo
    # Pod Security Admission: reject any pod that is not "restricted"-compliant
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
